### ISSUE TITLE
Latest version of QuantStack/ipycytoscape fails to build on binder

### ISSUE THREAD

**Issue by pwrose** [sbl-sdsc/neo4j-ipycytoscape#10]
@marimeireles I switched over to use the master branch of QuantStack/ipycytoscape.git instead of my own version pwrose/ipycytoscape.git, but I'm getting this error:

Pip subprocess error:
  Running command git clone -q https://github.com/QuantStack/ipycytoscape.git /tmp/pip-req-build-qvhgm48x
  ERROR: Command errored out with exit status 1:
   command: /srv/conda/envs/notebook/bin/python /srv/conda/envs/notebook/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmph2g1z4fa
       cwd: /tmp/pip-req-build-qvhgm48x
  Complete output (101 lines):
  /tmp/pip-build-env-qpjaxl2_/overlay/lib/python3.9/site-packages/setuptools/dist.py:642: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    warnings.warn(
  running bdist_wheel
  running jsdeps
  Installing build dependencies with npm.  This may take a while...
  > npm install

  added 1242 packages, and audited 1243 packages in 37s

  21 vulnerabilities (13 low, 5 moderate, 3 high)

  To address issues that do not require attention, run:
    npm audit fix

  To address all issues (including breaking changes), run:
    npm audit fix --force

  Run `npm audit` for details.
  npm notice
  npm notice New minor version of npm available! 7.7.6 -> 7.11.0
  npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.11.0>
  npm notice Run `npm install -g npm@7.11.0` to update!
  npm notice
  > npm run build

  > jupyter-cytoscape@1.2.0 build
  > npm run build:lib && npm run build:all

  > jupyter-cytoscape@1.2.0 build:lib
  > tsc

  > jupyter-cytoscape@1.2.0 build:all
  > npm run build:labextension && npm run build:nbextension

  > jupyter-cytoscape@1.2.0 build:labextension
  > npm run clean:labextension && jupyter labextension build .

  > jupyter-cytoscape@1.2.0 clean:labextension
  > rimraf ipycytoscape/labextension

  Traceback (most recent call last):
    File "/tmp/pip-build-env-qpjaxl2_/overlay/bin/jupyter-labextension", line 5, in <module>
      from jupyterlab.labextensions import main
    File "/tmp/pip-build-env-qpjaxl2_/overlay/lib/python3.9/site-packages/jupyterlab/__init__.py", line 7, in <module>
      from .labapp import LabApp
    File "/tmp/pip-build-env-qpjaxl2_/overlay/lib/python3.9/site-packages/jupyterlab/labapp.py", line 14, in <module>
      from jupyter_server._version import version_info as jpserver_version_info
    File "/tmp/pip-build-env-qpjaxl2_/overlay/lib/python3.9/site-packages/jupyter_server/__init__.py", line 15, in <module>
      from ._version import version_info, __version__
    File "/tmp/pip-build-env-qpjaxl2_/overlay/lib/python3.9/site-packages/jupyter_server/_version.py", line 5, in <module>
      from jupyter_packaging import get_version_info
  ImportError: cannot import name 'get_version_info' from 'jupyter_packaging' (/tmp/pip-build-env-qpjaxl2_/overlay/lib/python3.9/site-packages/jupyter_packaging/__init__.py)
  npm notice
  npm notice New minor version of npm available! 7.7.6 -> 7.11.0
  npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.11.0>
  npm notice Run `npm install -g npm@7.11.0` to update!
  npm notice
  Traceback (most recent call last):
    File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-qpjaxl2_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 221, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-qpjaxl2_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-qpjaxl2_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 123, in <module>
      setup(**setup_args)
    File "/tmp/pip-build-env-qpjaxl2_/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/srv/conda/envs/notebook/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/srv/conda/envs/notebook/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/srv/conda/envs/notebook/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-qpjaxl2_/overlay/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 503, in run
      [self.run_command(cmd) for cmd in cmds]
    File "/tmp/pip-build-env-qpjaxl2_/overlay/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 503, in <listcomp>
      [self.run_command(cmd) for cmd in cmds]
    File "/srv/conda/envs/notebook/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/srv/conda/envs/notebook/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-qpjaxl2_/overlay/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 274, in run
      c.run()
    File "/tmp/pip-build-env-qpjaxl2_/overlay/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 381, in run
      run(npm_cmd + ['run', build_cmd], cwd=node_package)
    File "/tmp/pip-build-env-qpjaxl2_/overlay/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 225, in run
      return subprocess.check_call(cmd, **kwargs)
    File "/srv/conda/envs/notebook/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/srv/conda/envs/notebook/bin/npm', 'run', 'build']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for ipycytoscape
ERROR: Could not build wheels for ipycytoscape which use PEP 517 and cannot be installed directly

CondaEnvException: Pip failed

time: 208.828

**Comment by marimeireles** [comment]
hey @pwrose, just a tip, if you put ``` around your code, kinda like you'd use "this" you can make it look like the following:

```
Pip subprocess error:
Running command git clone -q https://github.com/QuantStack/ipycytoscape.git /tmp/pip-req-build-qvhgm48x
ERROR: Command errored out with exit status 1:
command: /srv/conda/envs/notebook/bin/python /srv/conda/envs/notebook/lib/python3.9/site-packages/pip/_vendor/pep517/in_process.py build_wheel /tmp/tmph2g1z4fa
cwd: /tmp/pip-req-build-qvhgm48x
Complete output (101 lines):
/tmp/pip-build-env-qpjaxl2/overlay/lib/python3.9/site-packages/setuptools/dist.py:642: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
warnings.warn(
running bdist_wheel
running jsdeps
Installing build dependencies with npm. This may take a while...

    npm install

added 1242 packages, and audited 1243 packages in 37s

21 vulnerabilities (13 low, 5 moderate, 3 high)

To address issues that do not require attention, run:
npm audit fix

To address all issues (including breaking changes), run:
npm audit fix --force

Run npm audit for details.
npm notice
npm notice New minor version of npm available! 7.7.6 -> 7.11.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.11.0
npm notice Run npm install -g npm@7.11.0 to update!
npm notice

    npm run build

    jupyter-cytoscape@1.2.0 build
    npm run build:lib && npm run build:all

    jupyter-cytoscape@1.2.0 build:lib
    tsc

    jupyter-cytoscape@1.2.0 build:all
    npm run build:labextension && npm run build:nbextension

    jupyter-cytoscape@1.2.0 build:labextension
    npm run clean:labextension && jupyter labextension build .

    jupyter-cytoscape@1.2.0 clean:labextension
    rimraf ipycytoscape/labextension

Traceback (most recent call last):
File "/tmp/pip-build-env-qpjaxl2_/overlay/bin/jupyter-labextension", line 5, in
from jupyterlab.labextensions import main
File "/tmp/pip-build-env-qpjaxl2_/overlay/lib/python3.9/site-packages/jupyterlab/init.py", line 7, in
from .labapp import LabApp
File "/tmp/pip-build-env-qpjaxl2_/overlay/lib/python3.9/site-packages/jupyterlab/labapp.py", line 14, in
from jupyter_server.version import version_info as jpserver_version_info
File "/tmp/pip-build-env-qpjaxl2/overlay/lib/python3.9/site-packages/jupyter_server/init.py", line 15, in
from .version import version_info, version
File "/tmp/pip-build-env-qpjaxl2/overlay/lib/python3.9/site-packages/jupyter_server/version.py", line 5, in
from jupyter_packaging import get_version_info
ImportError: cannot import name 'get_version_info' from 'jupyter_packaging' (/tmp/pip-build-env-qpjaxl2/overlay/lib/python3.9/site-packages/jupyter_packaging/init.py)
npm notice
npm notice New minor version of npm available! 7.7.6 -> 7.11.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.11.0
npm notice Run npm install -g npm@7.11.0 to update!
npm notice
Traceback (most recent call last):
File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pip/vendor/pep517/in_process.py", line 280, in
main()
File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pip/vendor/pep517/in_process.py", line 263, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pip/vendor/pep517/in_process.py", line 204, in build_wheel
return build_backend().build_wheel(wheel_directory, config_settings,
File "/tmp/pip-build-env-qpjaxl2/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 221, in build_wheel
return self.build_with_temp_dir(['bdist_wheel'], '.whl',
File "/tmp/pip-build-env-qpjaxl2/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 207, in build_with_temp_dir
self.run_setup()
File "/tmp/pip-build-env-qpjaxl2/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
exec(compile(code, file, 'exec'), locals())
File "setup.py", line 123, in
setup(**setup_args)
File "/tmp/pip-build-env-qpjaxl2/overlay/lib/python3.9/site-packages/setuptools/init.py", line 153, in setup
return distutils.core.setup(**attrs)
File "/srv/conda/envs/notebook/lib/python3.9/distutils/core.py", line 148, in setup
dist.run_commands()
File "/srv/conda/envs/notebook/lib/python3.9/distutils/dist.py", line 966, in run_commands
self.run_command(cmd)
File "/srv/conda/envs/notebook/lib/python3.9/distutils/dist.py", line 985, in run_command
cmd_obj.run()
File "/tmp/pip-build-env-qpjaxl2/overlay/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 503, in run
[self.run_command(cmd) for cmd in cmds]
File "/tmp/pip-build-env-qpjaxl2/overlay/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 503, in
[self.run_command(cmd) for cmd in cmds]
File "/srv/conda/envs/notebook/lib/python3.9/distutils/cmd.py", line 313, in run_command
self.distribution.run_command(command)
File "/srv/conda/envs/notebook/lib/python3.9/distutils/dist.py", line 985, in run_command
cmd_obj.run()
File "/tmp/pip-build-env-qpjaxl2/overlay/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 274, in run
c.run()
File "/tmp/pip-build-env-qpjaxl2/overlay/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 381, in run
run(npm_cmd + ['run', build_cmd], cwd=node_package)
File "/tmp/pip-build-env-qpjaxl2/overlay/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 225, in run
return subprocess.check_call(cmd, **kwargs)
File "/srv/conda/envs/notebook/lib/python3.9/subprocess.py", line 373, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/srv/conda/envs/notebook/bin/npm', 'run', 'build']' returned non-zero exit status 1.

ERROR: Failed building wheel for ipycytoscape
ERROR: Could not build wheels for ipycytoscape which use PEP 517 and cannot be installed directly

CondaEnvException: Pip failed

time: 208.828
```

Which improves readability by a bunch! :)

**Comment by pwrose** [comment]
The latest version of ipywidgets solves this problem.

**Comment by marimeireles** [comment]
Sorry! I thought I had dealt with this.
Thanks!
